const fs = require("fs");
const path = require("path");
const axios = require("axios");

const currencyFlags = {
    "AUD": "https://flagcdn.com/w40/au.png",
    "CAD": "https://flagcdn.com/w40/ca.png",
    "CHF": "https://flagcdn.com/w40/ch.png",
    "CNY": "https://flagcdn.com/w40/cn.png",
    "EUR": "https://flagcdn.com/w40/eu.png",
    "GBP": "https://flagcdn.com/w40/gb.png",
    "HKD": "https://flagcdn.com/w40/hk.png",
    "IDR": "https://flagcdn.com/w40/id.png",
    "INR": "https://flagcdn.com/w40/in.png",
    "JPY": "https://flagcdn.com/w40/jp.png",
    "KRW": "https://flagcdn.com/w40/kr.png",
    "MYR": "https://flagcdn.com/w40/my.png",
    "NZD": "https://flagcdn.com/w40/nz.png",
    "PHP": "https://flagcdn.com/w40/ph.png",
    "SGD": "https://flagcdn.com/w40/sg.png",
    "THB": "https://flagcdn.com/w40/th.png",
    "TWD": "https://flagcdn.com/w40/tw.png",
    "VND": "https://flagcdn.com/w40/vn.png",
    "AED": "https://flagcdn.com/w40/ae.png",
    "AFN": "https://flagcdn.com/w40/af.png",
    "ALL": "https://flagcdn.com/w40/al.png",
    "AMD": "https://flagcdn.com/w40/am.png",
    "ANG": "https://flagcdn.com/w40/cw.png",
    "AOA": "https://flagcdn.com/w40/ao.png",
    "ARS": "https://flagcdn.com/w40/ar.png",
    "AWG": "https://flagcdn.com/w40/aw.png",
    "AZN": "https://flagcdn.com/w40/az.png",
    "BAM": "https://flagcdn.com/w40/ba.png",
    "BBD": "https://flagcdn.com/w40/bb.png",
    "BDT": "https://flagcdn.com/w40/bd.png",
    "BGN": "https://flagcdn.com/w40/bg.png",
    "BHD": "https://flagcdn.com/w40/bh.png",
    "BIF": "https://flagcdn.com/w40/bi.png",
    "BND": "https://flagcdn.com/w40/bn.png",
    "BOB": "https://flagcdn.com/w40/bo.png",
    "BRL": "https://flagcdn.com/w40/br.png",
    "BSD": "https://flagcdn.com/w40/bs.png",
    "BWP": "https://flagcdn.com/w40/bw.png",
    "BYN": "https://flagcdn.com/w40/by.png",
    "BZD": "https://flagcdn.com/w40/bz.png",
    "CDF": "https://flagcdn.com/w40/cd.png",
    "CLP": "https://flagcdn.com/w40/cl.png",
    "COP": "https://flagcdn.com/w40/co.png",
    "CRC": "https://flagcdn.com/w40/cr.png",
    "CVE": "https://flagcdn.com/w40/cv.png",
    "CZK": "https://flagcdn.com/w40/cz.png",
    "DJF": "https://flagcdn.com/w40/dj.png",
    "DKK": "https://flagcdn.com/w40/dk.png",
    "DOP": "https://flagcdn.com/w40/do.png",
    "DZD": "https://flagcdn.com/w40/dz.png",
    "EGP": "https://flagcdn.com/w40/eg.png",
    "ERN": "https://flagcdn.com/w40/er.png",
    "ETB": "https://flagcdn.com/w40/et.png",
    "FJD": "https://flagcdn.com/w40/fj.png",
    "GEL": "https://flagcdn.com/w40/ge.png",
    "GHS": "https://flagcdn.com/w40/gh.png",
    "GIP": "https://flagcdn.com/w40/gi.png",
    "GMD": "https://flagcdn.com/w40/gm.png",
    "GNF": "https://flagcdn.com/w40/gn.png",
    "GTQ": "https://flagcdn.com/w40/gt.png",
    "GYD": "https://flagcdn.com/w40/gy.png",
    "HNL": "https://flagcdn.com/w40/hn.png",
    "HTG": "https://flagcdn.com/w40/ht.png",
    "HUF": "https://flagcdn.com/w40/hu.png",
    "ILS": "https://flagcdn.com/w40/il.png",
    "IQD": "https://flagcdn.com/w40/iq.png",
    "IRR": "https://flagcdn.com/w40/ir.png",
    "ISK": "https://flagcdn.com/w40/is.png",
    "JMD": "https://flagcdn.com/w40/jm.png",
    "JOD": "https://flagcdn.com/w40/jo.png",
    "KES": "https://flagcdn.com/w40/ke.png",
    "KGS": "https://flagcdn.com/w40/kg.png",
    "KHR": "https://flagcdn.com/w40/kh.png",
    "KMF": "https://flagcdn.com/w40/km.png",
    "KWD": "https://flagcdn.com/w40/kw.png",
    "KZT": "https://flagcdn.com/w40/kz.png",
    "LAK": "https://flagcdn.com/w40/la.png",
    "LBP": "https://flagcdn.com/w40/lb.png",
    "LKR": "https://flagcdn.com/w40/lk.png",
    "LRD": "https://flagcdn.com/w40/lr.png",
    "LSL": "https://flagcdn.com/w40/ls.png",
    "LYD": "https://flagcdn.com/w40/ly.png",
    "MAD": "https://flagcdn.com/w40/ma.png",
    "MDL": "https://flagcdn.com/w40/md.png",
    "MGA": "https://flagcdn.com/w40/mg.png",
    "MKD": "https://flagcdn.com/w40/mk.png",
    "MMK": "https://flagcdn.com/w40/mm.png",
    "MNT": "https://flagcdn.com/w40/mn.png",
    "MOP": "https://flagcdn.com/w40/mo.png",
    "MRU": "https://flagcdn.com/w40/mr.png",
    "MUR": "https://flagcdn.com/w40/mu.png",
    "MVR": "https://flagcdn.com/w40/mv.png",
    "MWK": "https://flagcdn.com/w40/mw.png",
    "MXN": "https://flagcdn.com/w40/mx.png",
    "MZN": "https://flagcdn.com/w40/mz.png",
    "NAD": "https://flagcdn.com/w40/na.png",
    "NGN": "https://flagcdn.com/w40/ng.png",
    "NIO": "https://flagcdn.com/w40/ni.png",
    "NOK": "https://flagcdn.com/w40/no.png",
    "NPR": "https://flagcdn.com/w40/np.png",
    "OMR": "https://flagcdn.com/w40/om.png",
    "PAB": "https://flagcdn.com/w40/pa.png",
    "PEN": "https://flagcdn.com/w40/pe.png",
    "PGK": "https://flagcdn.com/w40/pg.png",
    "PKR": "https://flagcdn.com/w40/pk.png",
    "PLN": "https://flagcdn.com/w40/pl.png",
    "PYG": "https://flagcdn.com/w40/py.png",
    "QAR": "https://flagcdn.com/w40/qa.png",
    "RON": "https://flagcdn.com/w40/ro.png",
    "RSD": "https://flagcdn.com/w40/rs.png",
    "RUB": "https://flagcdn.com/w40/ru.png",
    "RWF": "https://flagcdn.com/w40/rw.png",
    "SAR": "https://flagcdn.com/w40/sa.png",
    "SBD": "https://flagcdn.com/w40/sb.png",
    "SCR": "https://flagcdn.com/w40/sc.png",
    "SDG": "https://flagcdn.com/w40/sd.png",
    "SEK": "https://flagcdn.com/w40/se.png",
    "SOS": "https://flagcdn.com/w40/so.png",
    "SRD": "https://flagcdn.com/w40/sr.png",
    "SSP": "https://flagcdn.com/w40/ss.png",
    "STN": "https://flagcdn.com/w40/st.png",
    "SVC": "https://flagcdn.com/w40/sv.png",
    "SYP": "https://flagcdn.com/w40/sy.png",
    "SZL": "https://flagcdn.com/w40/sz.png",
    "TJS": "https://flagcdn.com/w40/tj.png",
    "TMT": "https://flagcdn.com/w40/tm.png",
    "TND": "https://flagcdn.com/w40/tn.png",
    "TOP": "https://flagcdn.com/w40/to.png",
    "TRY": "https://flagcdn.com/w40/tr.png",
    "TTD": "https://flagcdn.com/w40/tt.png",
    "TZS": "https://flagcdn.com/w40/tz.png",
    "UAH": "https://flagcdn.com/w40/ua.png",
    "UGX": "https://flagcdn.com/w40/ug.png",
    "UYU": "https://flagcdn.com/w40/uy.png",
    "UZS": "https://flagcdn.com/w40/uz.png",
    "VES": "https://flagcdn.com/w40/ve.png",
    "VUV": "https://flagcdn.com/w40/vu.png",
    "WST": "https://flagcdn.com/w40/ws.png",
    "XAF": "https://flagcdn.com/w40/cf.png",
    "XCD": "https://flagcdn.com/w40/vc.png",
    "XOF": "https://flagcdn.com/w40/sn.png",
    "XPF": "https://flagcdn.com/w40/pf.png",
    "YER": "https://flagcdn.com/w40/ye.png",
    "ZAR": "https://flagcdn.com/w40/za.png",
    "ZMW": "https://flagcdn.com/w40/zm.png",
    "CUP": "https://flagcdn.com/w40/cu.png",
    "USD": "https://flagcdn.com/w40/us.png"
};

async function fetchAndConvertFlags() {
    let flagData = {};

    for (const [currency, url] of Object.entries(currencyFlags)) {
        try {
            const response = await axios.get(url, { responseType: "arraybuffer" });
            const base64 = Buffer.from(response.data).toString("base64");
            flagData[currency] = `data:image/png;base64,${base64}`;
        } catch (error) {
            console.error(`Failed to download ${currency}: ${error.message}`);
        }
    }
    console.log("🚀 Flags downloaded");

    // Save to JSON file
    fs.writeFileSync(
        path.join(__dirname, "currencyFlags.json"),
        JSON.stringify(flagData, null, 2)
    );

    console.log("✅ Flags saved to currencyFlags.json");
}

fetchAndConvertFlags();